### ISSUE TITLE
Error. Running fine on chrome but error for mobile.

### ISSUE THREAD

**Issue by KarthikeyanM3011** [codeyzx/sibestie#2]
keystorePropertiesFile. How to create this.

**Comment by codeyzx** [comment]
Hi @KarthikeyanM3011,

Thank you for raising this issue. Based on your description, the error you're experiencing is likely due to the absence of the `key.properties` file, which is required for signing the release build of your Flutter app for mobile platforms.

### Steps to Resolve:
1. **Create a `key.properties` file in the root directory of your project.**  
   This file should contain the following information:
   ```properties
   storePassword=<your_store_password>
   keyPassword=<your_key_password>
   keyAlias=<your_key_alias>
   storeFile=<path_to_your_keystore_file>
   ```

   Replace `<your_store_password>`, `<your_key_password>`, `<your_key_alias>`, and `<path_to_your_keystore_file>` with the actual values for your keystore. If you don't have a keystore yet, you can create one as described below.

2. **Generate a Keystore (if not already available):**
   Run the following command in your terminal to create a keystore:
   ```bash
   keytool -genkey -v -keystore <your_keystore_name>.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias <your_key_alias>
   ```
   - Replace `<your_keystore_name>` with the desired keystore filename.
   - Replace `<your_key_alias>` with a unique alias name.

3. **Update `build.gradle`:**
   Ensure your `build.gradle` file correctly references the `key.properties` file, as it already does in your current configuration.

4. **Debug Build for Testing:**  
   If you're testing locally and don't need release signing, you can temporarily bypass the signing step by ensuring the `buildTypes.release` block uses:
   ```gradle
   signingConfig signingConfigs.debug
   ```
   However, this is not recommended for production builds.

Let me know if you need further assistance! 😊
